# Generated by Django 6.0.5 on 2026-06-01 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='提取码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '提取码',
                'verbose_name_plural': '提取码',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=20, unique=True, verbose_name='QQ号')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '视频项目',
                'verbose_name_plural': '视频项目',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='访问IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('extraction_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='distribution.extractioncode', verbose_name='提取码')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.AddField(
            model_name='extractioncode',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_codes', to='distribution.member', verbose_name='会员'),
        ),
        migrations.AddField(
            model_name='extractioncode',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_codes', to='distribution.project', verbose_name='项目'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='视频标题')),
                ('video_file', models.FileField(upload_to='videos/%Y/%m/', verbose_name='视频文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='distribution.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.AlterUniqueTogether(
            name='extractioncode',
            unique_together={('project', 'member')},
        ),
    ]
