# Generated by Django 5.0.2 on 2026-06-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractioncode',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='提取码'),
        ),
    ]
