# Generated by Django 5.0.2 on 2026-06-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_extractioncode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractioncode',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='提取码'),
        ),
    ]
